### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pypingou** [praiskup/pre-receive-hooks#1]
There is no license specified anywhere here :)

**Comment by praiskup** [comment]
Is public domain fine?

**Comment by praiskup** [comment]
7cbcd5e181e466b965b83157431d2a268c002aa6 feel free to take what's useful IOW, I guess this is going to be hosted on different place (if ever used) anyway

**Comment by pypingou** [comment]
thanks for clarifying, note that CC0 is a better license than public domain which is problematic in some countries (such as France), but that's a little nitpick :)

**Comment by praiskup** [comment]
Feel free to use it/relicence under CC0, I hope that this is allowed by Public Domain.

More interesting to me is "howto get this code involved in pagure" to make the
packages a bit cleaner.  Can I help with this?

**Comment by pypingou** [comment]
This would be done by the Fedora Infrastructure, just open a ticket for it (iirc, there is even already one)
